[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "django-filepond"
authors = [
    {name = "Jochen Wersdörfer", email = "jochen-filepond@wersdoerfer.de"},
]
dynamic = ["version", "description"]
requires-python = ">=3.9"
keywords = [
    "upload",
    "filepond",
    "django",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python",
    "Framework :: Django",
    "License :: OSI Approved :: BSD License",
    "Topic :: Internet",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
    "Development Status :: 3 - Alpha",
    "Environment :: Web Environment",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]

dependencies = [
    "Django",
    "django-model-utils",
]

[project.optional-dependencies]
test = [
    "django-environ",
    "factory-boy",
    "Pillow",
    "pytest >= 6",
    "pytest-cov >= 3",
    "pytest-django",
]
doc = [
    "sphinx-rtd-theme",
]
dev = [
    "black",
    "flake8",
    "isort",
    "tox",
]

[project.urls]
Documentation = "https://django-filepond.readthedocs.io/"
Source = "https://github.com/ephes/django-filepond"

[tool.flit.module]
name = "filepond"

[tool.isort]
profile = "black"

[tool.black]
line-length = 119

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "tests.settings"
minversion = "6.0"
testpaths = ["tests"]
filterwarnings = [
    "ignore::django.utils.deprecation.RemovedInDjango50Warning",
    "ignore::DeprecationWarning",
]
addopts = [
    "--reuse-db",
    "--no-migrations",
]
norecursedirs = [
    ".git",
    "docs",
]
